site_name: Figurate
site_url: https://www.figurate.org
theme:
  name: material
  favicon: images/favicon.png
  logo: images/logo.png
  features:
    - tabs
repo_url: https://github.com/figurate/figurate-docs
repo_name: figurate/figurate-docs
google_analytics:
  - UA-402774-9
  - auto
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/benfortuna
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/benfortuna
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/micronode
nav:
  - Home:
    - Introduction: index.md
  - Infrastructure as Code:
    - Overview: iac/index.md
    - Terraform:
        - Introduction: iac/terraform/index.md
        - AWS: iac/terraform/aws.md
        - Digital Ocean: iac/terraform/digitalocean.md
  - Modular Architecture:
    - Overview: modularity/index.md
    - OSGi:
        - Introduction: modularity/osgi/index.md
        - Getting Started: modularity/osgi/getting-started.md
        - Release Notes: modularity/osgi/release-notes.md
    - Docker:
        - Introduction: modularity/docker/index.md
    - Lambda:
        - Introduction: modularity/lambda/index.md
  - Orchestration:
      - Overview: orchestration/index.md
      - Gradle:
          - Overview: orchestration/gradle/index.md
